import pygame

TITLE = "Snake"

ROWS = 24
COLS = 32
SQUARE_SIZE = 32
WINDOW_WIDTH = COLS * SQUARE_SIZE
WINDOW_HEIGHT = ROWS * SQUARE_SIZE


LINE_COLOR = pygame.Color("black")
LINE_COLOR.a = 128


BACKGROUND_COLOR = pygame.Color("gray")